### ISSUE TITLE
Generate keys

### ISSUE THREAD

**Issue by krakke** [TinyMan/node-jeanne#2]
Could not read [ key ] file. Check your paths.
Could not read [ cert ] file. Check your paths.

How do i generate keys?

Also

`jeanne:voice` Error: Cannot find module '/home/bot/node-jeanne/data/voice/map.json'

Would love some more install hints

**Comment by TinyMan** [comment]
The way I used to generate keys is with mumble client, and then place the file at the right location. But for a starter you can just remove keys and cert lines from config and connect without cert. If there is a password you can set it in config file.

Another way is to use openssl as specified [here](https://github.com/Rantanen/node-mumble) but I didn't test it: 
`openssl req -x509 -newkey rsa:2048 -nodes -keyout key.pem -out cert.pem` 

For voice extension to work (voice pun/samples), you need voice samples into a folder, and a map that classifies samples / categories. Going to work on a Wiki page for this. In the meanwhile the extension should simply not activate.

**Comment by TinyMan** [comment]
You can read about voice extension in the [wiki](https://github.com/TinyMan/node-jeanne/wiki/Enabling-Jeanne-to-talk), and I've added default/example voice config/map file and samples.
