### ISSUE TITLE
!radio doesn't work

### ISSUE THREAD

**Issue by Perdouille** [TinyMan/node-jeanne#4]
Hello ! Sorry for bothering you again ! I tried to listen to radios (!radio NRJ, ...) and it does say "Streaming NRJ" but there's no sound at all nor any error message. I tried with multiple radios, and listening to the stream on Firefox works well. !yt works too

Any idea ? 

Thanks !

**Comment by TinyMan** [comment]
That's weird, I didn't manage to reproduce it yet.

I'll look into it, try to add some more logging and see.

**Comment by Perdouille** [comment]
Still nothing, even in the logs. I tried with "!radio "http://cdn.nrjaudio.fm/audio1/fr/30001/mp3_128.mp3?origine=listenlive" and "!radio "http://cdn.nrjaudio.fm/audio1/fr/30001/mp3_128.mp3"

I may miss a dependency, but I can't find it. Everything else seems to work

**Comment by TinyMan** [comment]
You mean `!radio http://cdn.nrjaudio.fm/audio1/fr/30001/mp3_128.mp3` (without quotes)

Can you post the result of `npm list --depth=0` ?

**Comment by Perdouille** [comment]
Yes sorry, no quotes

Here's the result of the command 

`jeanne@0.6.0 /home/perdouille/Jeanne/node-jeanne
├── app-module-path@2.2.0
├── autolink-js@1.0.2
├── cheerio@0.22.0
├── debug@2.6.8
├── es6-promisify@5.0.0
├── file-type@3.9.0
├── fixedqueue@0.0.1
├── fluent-ffmpeg@2.1.2
├── google-speech@0.0.5 (git+https://github.com/TinyMan/google-speech.git#0098ac238f98033be4b84b1fcb4451d594904e35)
├── googleapis@20.1.0
├── html-to-text@3.3.0
├── jamy@0.2.1
├── mumble@0.3.11 (git+https://github.com/TinyMan/node-mumble.git#373070c31fcfb153edb0dc291785c3479fcbef7e)
├── parse-youtube-user@0.0.2
├── request@2.81.0
├── sqlite3@3.1.8
├── stumble@1.1.1
├── sylvia@0.1.0
├── timed-stream@1.1.0
├── youtube-node@1.3.2
└── ytdl-core@0.14.4`

**Comment by TinyMan** [comment]
Your deps seem alright. What's your ffmpeg's version ? 
Can you do `ffmpeg http://cdn.nrjaudio.fm/audio1/fr/30001/mp3_128.mp3?origine=listenlive test.mp3`,
after a while `ctrl+c` and play the file ?

**Comment by Perdouille** [comment]
It's version 2.6.9. The command doesn't work 

>ffmpeg version 2.6.9 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Debian 4.9.2-10)
  configuration: --prefix=/usr --extra-cflags='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security ' --extra-ldflags='-Wl,-z,relro' --cc='ccache cc' --enable-shared --enable-libmp3lame --enable-gpl --enable-nonfree --enable-libvorbis --enable-pthreads --enable-libfaac --enable-libxvid --enable-postproc --enable-x11grab --enable-libgsm --enable-libtheora --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libx264 --enable-libspeex --enable-nonfree --disable-stripping --enable-libvpx --enable-libschroedinger --disable-encoder=libschroedinger --enable-version3 --enable-libopenjpeg --enable-librtmp --enable-avfilter --enable-libfreetype --enable-libvo-aacenc --disable-decoder=amrnb --enable-libvo-amrwbenc --enable-libaacplus --libdir=/usr/lib/x86_64-linux-gnu --disable-vda --enable-libbluray --enable-libcdio --enable-gnutls --enable-frei0r --enable-openssl --enable-libass --enable-libopus --enable-fontconfig --enable-libpulse --disable-mips32r2 --disable-mipsdspr1 --disable-mipsdspr2 --enable-libvidstab --enable-libzvbi --enable-avresample --disable-htmlpages --disable-podpages --enable-libutvideo --enable-libfdk-aac --enable-libx265 --enable-libiec61883 --enable-vaapi --enable-libdc1394 --disable-altivec --shlibdir=/usr/lib/x86_64-linux-gnu
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Output #0, mp3, to 'test.mp3':
Output file #0 does not contain any stream

I'm installing latest ffmpeg version by compiling the source, let's see if it works

**Comment by Perdouille** [comment]
It works with the newest version of ffmpeg ! I installed it from jessie-backports
